# Generated by Django 3.2.7 on 2021-09-29 18:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('address', models.CharField(default='', max_length=400)),
                ('city', models.CharField(default='', max_length=200)),
                ('postal_code', models.CharField(default='', max_length=6)),
                ('website', models.CharField(default='', max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
