# Generated by Django 3.2.7 on 2021-09-29 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0005_alter_dealer_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealer',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='dealer',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
    ]
