# Generated by Django 3.2.7 on 2021-09-29 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0006_auto_20210929_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealer',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='dealer',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=9),
        ),
    ]
