# Generated by Django 3.2.7 on 2021-09-29 20:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0008_alter_dealer_api_key'),
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trim', models.CharField(default='', max_length=100)),
                ('year', models.CharField(default='', max_length=6)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('special_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vin', models.CharField(default='', max_length=20)),
                ('date_removed', models.DateTimeField(blank=True)),
                ('mileage', models.IntegerField(blank=True, default=0)),
                ('images_count', models.IntegerField(blank=True, default=0)),
                ('condition', models.CharField(choices=[('used', 'Used'), ('new', 'New')], default='used', max_length=4)),
                ('raw_exterior_color', models.CharField(blank=True, default='', max_length=100)),
                ('raw_interior_color', models.CharField(blank=True, default='', max_length=100)),
                ('raw_body_style', models.CharField(blank=True, default='', max_length=100)),
                ('raw_transmission', models.CharField(blank=True, default='', max_length=100)),
                ('raw_fuel_type', models.CharField(blank=True, default='', max_length=100)),
                ('raw_drivetrain', models.CharField(blank=True, default='', max_length=100)),
                ('dealer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dealers', to='dealers.dealer')),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cars', to='cars.model')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
