# Generated by Django 3.2.7 on 2021-09-29 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='special_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
    ]
