# Generated by Django 3.2.7 on 2021-09-29 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_alter_car_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='date_removed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
