# Generated by Django 3.2.7 on 2021-10-03 20:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_auto_20211002_0945'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarHistory',
            fields=[
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field', models.CharField(default='', max_length=40)),
                ('value', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='histories', to='cars.car')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
